---
branches:
  - main
  - { name: next, prerelease: true }
tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - { breaking: true, release: major }
        - { type: feat, release: minor }
        - { type: refactor, scope: "core*", release: minor }
        - { revert: true, release: patch }
        - { type: deps, release: patch }
        - { type: fix, release: patch }
        - { type: perf, release: patch }
        - { type: refactor, release: patch }
        - { type: docs, release: false }
        - { scope: no-release, release: false }

  - - "@semantic-release/release-notes-generator"
    - preset: angular

  - - "@semantic-release/npm"
    - npmPublish: false

  - - "@semantic-release/github"
    - addReleases: bottom
      assignees: trevor-anderson

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file.

        ---

  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md", "package.json", "package-lock.json", "npm-shrinkwrap.json"]
      message: "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
