/* eslint-disable */
/* prettier-ignore */

// Stripe Connect ToS info here https://stripe.com/docs/connect/updating-accounts#tos-acceptance

export const ENGLISH = `Payment processing services for [account holder term, e.g. drivers or sellers] on [platform name] are provided by Stripe and are subject to the Stripe Connected Account Agreement, which includes the Stripe Terms of Service (collectively, the “Stripe Services Agreement”). By agreeing to [this agreement / these terms / etc.] or continuing to operate as a [account holder term] on [platform name], you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of [platform name] enabling payment processing services through Stripe, you agree to provide [platform name] accurate and complete information about you and your business, and you authorize [platform name] to share it and transaction information related to your use of the payment processing services provided by Stripe.`;
export const FRENCH = `Les services de paiement pour les [terme désignant les détenteurs de compte: marchands, chauffeurs, porteurs de projet...] officiant sur [nom de la plateforme] sont fournis par Stripe et soumis à l’Accord sur les comptes Stripe Connected (Stripe Connected Account Agreement), qui inclut les Modalités de service de Stripe (l’ensemble étant appelé les “Conditions Générales d’Utilisation Stripe” - “Stripe Services Agreement”.) En agréant aux présentes [Conditions Générales d’Utilisation / de Vente] ou en continuant à opérer en tant que [terme désignant les détenteurs de compte] officiant sur [nom de la plateforme], vous acceptez d’être lié aux Conditions Générales d’Utilisation Stripe, celles-ci pouvant occasionnellement faire l’objet de modifications de la part de Stripe. Du fait que [nom de la plateforme] permette d’effectuer les paiements via Stripe, vous acceptez de fournir à [nom de la plateforme] des informations précises et complètes sur vous et votre activité, et autorisez [nom de la plateforme] à partager ces informations ainsi que celles concernant les transactions effectuées via la solution de paiement fournie par Stripe.`;
export const SPANISH = `Los servicios de procesamiento de pago para [término de titular de cuenta, p.ej. conductor o vendedor] en [nombre de plataforma] son proporcionados por Stripe y están sujetos al Acuerdo de cuentas conectadas de Stripe (Stripe Connected Account Agreement), que incluye los Términos de servicio de Stripe (Stripe Terms of Service), en conjunto, el “Acuerdo de servicio de Stripe” (“Stripe Services Agreement”). Al aceptar [este acuerdo / estos términos / etc.] o seguir operando como [término de titular de cuenta] en [nombre de plataforma], usted acepta cumplir las obligaciones del Acuerdo de servicios de Stripe, que puede ser modificado por Stripe de tanto en tanto. Para que [nombre de plataforma] pueda ofrecer servicios de procesamiento de pagos a través de Stripe, usted acepta proporcionar a [nombre de plataforma] información completa y exacta sobre usted y su negocio, y autoriza a [nombre de plataforma] a compartir dicha información y los datos de las transacciones relacionadas con el uso de los servicios de procesamiento de pago proporcionados por Stripe.`;
export const ITALIAN = `I servizi di elaborazione dei pagamenti per [termine definito dal proprietario dell’account, come “conducenti”, “venditori”, ecc.] su [nome piattaforma] sono forniti da Stripe e sono soggetti alle condizioni dell’Accordo relativo agli account connessi Stripe (Stripe Connected Account Agreement), che include i Termini del servizio Stripe (Stripe Terms of Service), collettivamente detti “Accordo sui servizi Stripe” (“Stripe Services Agreement”). Accettando [questo accordo, i suddetti termini, ecc.] o continuando a operare in qualità di [termine definito dal proprietario dell’account] su [nome piattaforma], l’utente accetta di essere vincolato all’Accordo sui servizi Stripe e alle eventuali modifiche apportate da Stripe di tanto in tanto. Affinché [nome piattaforma] possa offrire detti servizi di elaborazione dei pagamenti tramite Stripe, l’utente accetta di fornire a [nome piattaforma] informazioni accurate e complete sull’utente e sulla sua azienda, e autorizza [nome piattaforma] a condividere tali informazioni e i dati delle transazioni correlate con l’utilizzo dei servizi di elaborazione dei pagamenti forniti da Stripe.`;
export const PORTUGUESE = `Os serviços de processamento de pagamento de [account holder term, e.g. drivers or sellers] em [platform name] são fornecidos pela Stripe e estão sujeitos ao Stripe Connected Account Agreement (Contrato de Conta Vinculada da Stripe), que inclui os Stripe Terms of Service(Termos de Serviço da Stripe, conjuntamente, “Stripe Services Agreement”, Contrato de Serviços da Stripe). Ao concordar com [this agreement / these terms / etc.] ou continuar a operar como [account holder term] em [platform name], você aceita o Contrato de Serviços da Stripe, que pode ser alterado pela Stripe periodicamente. Como condição da utilização de serviços de processamento de pagamento pela [platform name] por meio da Stripe, você concorda em fornecer a [platform name] informações precisas e completas sobre você e sua empresa e autoriza [platform name] a compartilhá-las, além das informações de transações relacionadas ao seu uso dos serviços de processamento de pagamento fornecidos pela Stripe.`;
export const GERMAN = `Zahlungsdienstleistungen für [Beschreibung des Account-Inhabers, z.B. Reinigungskraft oder Verkäufer] auf [Name der Plattform] werden von Stripe erbracht und unterliegen der Stripe Connected Account Vereinbarung (Stripe Connected Account Agreement), welche die Stripe Nutzungsbedingungen (Stripe Terms of Service) beinhaltet (zusammengefasst unter dem Sammelbegriff “Stripe Services Agreement”). Durch die Zustimmung zu den vorliegenden [Nutzungsbedingungen, Bedingungen, ...] oder das weitere agieren als [Beschreibung des Account-Inhaber, z.B. Reinigungskraft oder Verkäufer] auf [Name der Plattform], akzeptieren Sie die Bedingungen der Vereinbarung “Stripe Services Agreement”, welche von Stripe von Zeit zu Zeit angepasst werden darf. Als Voraussetzung, dass [Name der Plattform] die Zahlungsdienstleistungen von Stripe in Anspruch nehmen kann, stimmen Sie zu, vollständige und komplette Informationen über sich und ihr Unternehmen für [Name der Plattform] bereitzustellen, und sie autorisieren [Name der Plattform], diese Informationen und Transaktionsinformationen, die im Zusammenhang mit ihrer Nutzung der von Stripe offerierten Zahlungsdienstleistungen stehen, weiterzugeben.`;
export const JAPANESE = `[プラットフォームの名称]における[アカウント所有者を示す文言（例えばドライバー又は売り手）]向けの支払処理サービスは、Stripeが提供し、Stripe Connectアカウント契約（Stripe利用規約を含み、総称して「Stripeサービス契約」といいます。）に従うものとします。[本契約、本条件等]への同意又は[プラットフォームの名称]において[アカウント所有者を示す文言]としての取引の継続により、お客様はStripeサービス契約（随時Stripeにより修正されることがあり、その場合には修正されたものを含みます。）に拘束されることに同意するものとします。 Stripeを通じた支払処理サービスを[プラットフォームの名称]ができるようにするための条件として、お客様は、[プラットフォームの名称]に対してお客様及びお客様の事業に関する正確かつ完全な情報を提供することに同意し、[プラットフォームの名称]が当該情報及びStripeが提供する支払処理サービスのお客様による使用に関連する取引情報を共有することを認めるものとします。`;

const _STRIPE_LEGAL_LINK = `https://stripe.com/connect-account/legal`;
const _STRIPE_ToS_LINK = `https://stripe.com/legal`;
