name: Release Workflow

# This workflow is called by the Test workflow when all tests pass.

on:
  workflow_dispatch:
  workflow_call: # may be called by the Test workflow
    secrets:
      SEMANTIC_RELEASE_TOKEN: { required: true }

jobs:
  release:
    name: Release
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/release.yaml@main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
