#!/usr/bin/env bash
####################################################################################
# This script downloads the Fixit OpenAPI Schema and uses it to generate types.
####################################################################################

# Download the latest version of the Fixit OpenAPI Schema
npx swaggerhub api:get Nerdware/Fixit > open-api.yaml

# Update OpenAPI types using NodeJS API from openapi-typescript to fix `Date` types.
# (Their CLI does not convert `format: date-time` values to `Date` types)

node --input-type=module -e "
import fs from 'node:fs';
import ts from 'typescript';
import openapiTS, { astToString } from 'openapi-typescript';

const DATE = ts.factory.createIdentifier('Date');
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull());

const ast = await openapiTS(
	new URL('file://$PWD/open-api.yaml'),
	{
		transform(schemaObject, metadata) {
			if (schemaObject.format === 'date-time') {
				return Array.isArray(schemaObject.type) && schemaObject.type.includes('null')
					? ts.factory.createUnionTypeNode([DATE, NULL])
					: DATE;
			}
		},
	}
);

const tsFileContents = \`\
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

\${astToString(ast)}
\`;

fs.writeFileSync('src/types/__codegen__/open-api.ts', tsFileContents);"

# Finally, delete the open-api.yaml file
rm open-api.yaml

###############################################################################
