name: Release Workflow

on:
  workflow_dispatch:
  workflow_call: # may be called by the Test workflow
    secrets:
      SEMANTIC_RELEASE_TOKEN: { required: true }
  push:
    branches: [main, next]
    paths: ["src/**/*", "package*.json", "index.html"]

jobs:
  release:
    name: Release
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/release.yaml@main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
