name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main, next]
    paths:
      - "src/**/*"
      - "package*.json"
      - "public/**/*"
      - ".github/workflows/test.yaml"
  push:
    branches: [main, next]
    paths:
      - "src/**/*"
      - "package*.json"
      - "public/**/*"
      - ".github/workflows/test.yaml"

env:
  NODE_ENV: test
  SKIP_PREFLIGHT_CHECK: true
  REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
  REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_TEST_PUBLISHABLE_KEY }}
  REACT_APP_STRIPE_VIP_PROMO_CODE: ${{ secrets.REACT_APP_STRIPE_VIP_PROMO_CODE }}
  REACT_APP_API_BASE_URL: http://localhost:80
  REACT_APP_ROUTER_PATH_BASE: /

jobs:
  test:
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/node_test.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
