name: Upload Staging to S3 Workflow

# Split workload_upload_to_s3 into separate prod/staging workflows since
# calling workflows can't pass env vars to called workflows, and the prod
# and staging builds need to have varying env vars provided at build time.
# Having separate workflows for prod/staging which set env vars at the top
# is the simplest solution.

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      bucket_target_dir:
        description: The target S3 bucket path/dirname.
        required: true
        type: string

env:
  # Build env vars specific to staging env:
  NODE_ENV: staging
  REACT_APP_API_BASE_URI: staging.gofixit.app
  REACT_APP_API_PROTOCOL: https
  REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_TEST_PUBLISHABLE_KEY }}

jobs:
  build_and_upload:
    name: Deploy
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/upload_to_s3.yaml@main
    with:
      s3-target-dest: ${{ secrets.S3_BUCKET_NAME }}/${{ inputs.bucket_target_dir }}
      s3-sync-command-params: "--acl bucket-owner-full-control --sse AES256 --delete"
    secrets:
      OIDC_GITHUB_ROLE_ARN: ${{ secrets.OIDC_GITHUB_ROLE_ARN }}
      S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
    # permissions required to use aws-actions/configure-aws-credentials@v1
    permissions:
      id-token: write
      contents: read
