name: Test Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
  NODE_ENV: test
  VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_TEST_PUBLISHABLE_KEY }}
  VITE_API_PROTOCOL: http
  VITE_API_HOST: localhost:8080
  # TODO Once fixit-api dev Docker img is available, impl docker-compose for int tests.

jobs:
  test:
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/node_test.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
